backend = "glx";
vsync = true;

fading = true;
fade-in-step = 0.06;
fade-out-step = 0.06;

rules = (
  # dim unfocused windows
  { match = "!focused"; dim = 0.3; },

	# never dim popups, menus, tooltips
  { match = "window_type = 'popup_menu' || window_type = 'dropdown_menu' || window_type = 'menu' || window_type = 'tooltip' || window_type = 'utility'"; dim = 0; },

  # never dim browsers
  { match = "class_g = 'Brave-browser'"; dim = 0; },
  { match = "class_g = 'firefox'"; dim = 0; },

	# never dim rofi
	{ match ="class_g= 'Rofi'"; dim = 0; fade = false; },

	# never dim mpv
	{ match ="class_g= 'mpv'"; dim = 0; },

	# never dim i3bar and dunst
	{ match = "class_g = 'i3bar'"; dim=0; shadow = false; },
	{ match = "class_g = 'Dunst'"; dim=0; shadow = false; }
)
