#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively restart Ripgrep with reload action
# 3. Open the file in Vim
RG_PREFIX="rg --column --line-number --no-heading --color=always --follow --smart-case --hidden "
INITIAL_QUERY="${*:-}"
IFS=: read -ra selected < <(
	FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
		fzf --ansi \
			--color "hl:-1:underline,hl+:-1:underline:reverse" \
			--disabled --query "$INITIAL_QUERY" \
			--bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
			--prompt "Rg> " \
			--delimiter : \
			--info inline \
			--height 50% \
			--layout reverse \
			--preview 'bat {1} --highlight-line {2}' \
			--preview-window 'right,50%,+{2}+4/4,~4'
)
# [ -n "${selected[0]}" ] && vim "${selected[0]}" "+${selected[1]}"
inject $selected
