gui:
  showIcons: true
  theme:
    lightTheme: false
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white

git:
  paging:
    colorArg: always
    pager: delta --paging=never --24-bit-color=never
